Migration to Integration Service: is-websocket and is-websocket-test packages
eProsima/WebSocket-SH pull request #1
Opened 2021-03-31 14:52 UTC by jamoralp

2021-04-06 06:37 UTC, jamoralp commented
@FranFin please review the doxygen comments in the code

2021-04-09 06:40 UTC, laura-eprosima requested changes

2021-04-09 06:40 UTC, laura-eprosima commented on websocket-test/integration/websocket__roundtrip.cpp
> +    // Integration Service. An i::sh::mock subscription will never receive a
```suggestion
    // Integration Service. An is::sh::mock subscription will never receive a
```

2021-04-09 06:40 UTC, laura-eprosima commented on websocket/src/Client.cpp
> +                        << "Error creating connection handle: " << ec.message() << std::endl;
```suggestion
                        << "Creation of connection handle failed: " << ec.message() << std::endl;
```

2021-04-09 06:43 UTC, laura-eprosima approved these changes

2021-04-09 07:08 UTC, merged