Rearrange folders
eProsima/WebSocket-SH pull request #8
Opened 2021-04-27 13:49 UTC by jamoralp

Signed-off-by: Jose Antonio Moral <joseantoniomoralparras@gmail.com>

2021-04-27 14:00 UTC, jamoralp commented on .github/workflows/ci.yml
> +          git clone --recursive -b feature/json-xtypes-to-core https://github.com/eProsima/Integration-Service src/integration-service
Revert this:
```suggestion
          git clone --recursive https://github.com/eProsima/Integration-Service src/integration-service
```

2021-04-27 14:23 UTC, laura-eprosima requested changes

2021-04-27 14:23 UTC, laura-eprosima commented on test/unitary/paths.cpp
> + * Copyright (C) 2020 Open Source Robotics Foundation
This file is autogenerated and it should not be here

2021-04-28 05:59 UTC, laura-eprosima approved these changes

2021-04-28 06:00 UTC, merged